name: Bug report
description: Report found issue with SkySlots
labels: ["bug", "pending triage"]
assignees: ["vainnor"]
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        Hello! Thank you for reporting an issue with SkySlots.
        
        Before reporting, please also check existing issues in this repository - you can filter them by "bug" label (also check closed ones).
        
  - type: input
    id: id
    attributes:
      label: Your Vatsim CID
      description: It is your Vatsim login.
  - type: input
    id: version
    attributes:
      label: SkySlots Version
      description: Please include SkySlots version - you can find it in the footer
      placeholder: For example, 0.1.1
    validations:
      required: 
  - type: textarea
    id: what
    attributes:
      label: Describe your issue
      description: Please tell us what's happening, what is expected and actual result. Include some screenshots and videos if there are some!
  - type: textarea
    id: how
    attributes:
      label: Reproduction steps
      description: Please describe how can we reproduce this issue - even if it's obvious. If your issue relates to some controller or specific user, include callsign(s) and cid(s). If it's hard to reproduce, a video would be nice to see.
  - type: input
    id: platform
    attributes:
      label: Platform
      description: Specify your platform (windows, macos, ios, android), as well as browser and it's version
  - type: textarea
    id: additional
    attributes:
      label: Additional info
      description: Is there something additional we need to know? Please tell us!
  - type: checkboxes
    id: validation
    attributes:
      label: Validation
      description: Please validate your report
      options:
        - label: I have searched for other issues and didn't found any alike
